INSERT INTO TASK (NAME, DESCRIPTION ) VALUES ('task1', 'first task');
INSERT INTO TASK (NAME, DESCRIPTION ) VALUES ('task2', 'second task');
INSERT INTO TASK (NAME, DESCRIPTION ) VALUES ('task3', 'third task');
INSERT INTO TASK (NAME, DESCRIPTION ) VALUES ('task4', 'fourth task');